name: atc_companion
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.2
  enum_to_string: ^1.0.8
  request_state: ^0.1.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
